name: .NET 8.0 Console Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

  create-release:
    permissions: write-all
    needs: build
    runs-on: windows-latest
    steps:
    - name: Generate release tag
    id: generate_release_tag
    uses: alexvingg/next-release-tag@v1.0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.get_tag.outputs.tag }}
        release_name: Release ${{ github.sha }}
        body: Automated release created by GitHub Actions
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
