name: .NET 8.0 Console Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Zip Build
      run: Compress-Archive -Path ./bin/Release/net8.0/* -DestinationPath Release.zip

  create-release:
    permissions:
      contents: write
    needs: build
    runs-on: windows-latest
    steps:
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: v${{ github.run_number }}
        body: Automated release created by GitHub Actions
        draft: false
        prerelease: false
        files: Release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}